services:
    tus-server-local:
        # container_name: tus-server-local
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: biescloudtechsupport/node:24.0-slim-260325
        working_dir: /usr/local/app
        command: booting tus-server_init.sh dev
        # networks:
        #     modlib:
        #         aliases:
        #             - modlib.tus-server-local
        ports:
            - ${TARGET_HOST}:${TUS_SERVER_PORT}:${TUS_SERVER_PORT}
        # depends_on:
        #     - postgresql
        #     - minio
        #     - redis
        # env_file:
        #     - ./.env
        volumes: 
            - ./:/usr/local/app
        logging:
            driver: "json-file"
            options:
                max-size: "2m"   # 單個檔案最大 2MB
                max-file: "15" 
        restart: unless-stopped